version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "solucao#2021"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    cpus: "0.5"
    mem_limit: 2048m
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
  solucao-api:
    image: solucao-api
    cpus: "0.5"
    mem_limit: 50m
    build: 
      context: .
      dockerfile: Solucao.API/Dockerfile
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "SA"
      Password: "solucao#2021"
      Database: "SolucaoDB"
    ports: 
      - "8090:80"

        