apiVersion: v1
kind: Service
metadata:
  name: solucao-api-service
  labels:
    app: solucao-api-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: solucao-api-service